const fs = require('fs');
const h = [];
h.push('<!DOCTYPE html>');
h.push('<html lang="en" dir="ltr">');
h.push('<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">');
h.push('<title>ERD - Media Deck</title>');
h.push('<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></scr'+'ipt>');
h.push('<style>');
h.push(':root{--bg:#0f172a;--sf:#1e293b;--bd:#334155;--tx:#e2e8f0;--tm:#94a3b8;--ac:#38bdf8;--a2:#a78bfa;--a3:#34d399;--a4:#fb923c;--a5:#f472b6}');
h.push('*{margin:0;padding:0;box-sizing:border-box}');
h.push('body{background:var(--bg);color:var(--tx);font-family:Segoe UI,Tahoma,sans-serif}');
h.push('.hdr{background:var(--sf);border-bottom:1px solid var(--bd);padding:20px 32px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px}');
h.push('.hdr h1{font-size:22px;font-weight:700;background:linear-gradient(135deg,var(--ac),var(--a2));-webkit-background-clip:text;-webkit-text-fill-color:transparent}');
h.push('.hdr .sub{color:var(--tm);font-size:13px}');
h.push('.stats{display:flex;gap:16px;flex-wrap:wrap}');
h.push('.stat{background:var(--bg);border:1px solid var(--bd);border-radius:8px;padding:8px 16px;text-align:center}');
h.push('.stat .n{font-size:20px;font-weight:700;color:var(--ac)}');
h.push('.stat .l{font-size:11px;color:var(--tm)}');
h.push('.tabs{display:flex;background:var(--sf);border-bottom:1px solid var(--bd);padding:0 32px}');
h.push('.tab{padding:10px 20px;font-size:13px;color:var(--tm);cursor:pointer;border:none;border-bottom:2px solid transparent;background:none;font-family:inherit;transition:all .2s}');
h.push('.tab:hover{color:var(--tx)}.tab.on{color:var(--ac);border-bottom-color:var(--ac);font-weight:600}');
h.push('.ct{padding:24px 32px}');
h.push('.v{display:none}.v.on{display:block}');
h.push('.mermaid{display:flex;justify-content:center;overflow:auto;padding:20px 0}.mermaid svg{max-width:100%;height:auto}');
h.push('.g{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}');
h.push('.tc{background:var(--sf);border:1px solid var(--bd);border-radius:10px;overflow:hidden;transition:transform .2s,box-shadow .2s}');
h.push('.tc:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.3)}');
h.push('.tch{padding:12px 16px;font-weight:700;font-size:14px;display:flex;align-items:center;gap:8px}');
h.push('.tch .b{font-size:10px;padding:2px 8px;border-radius:10px;font-weight:600}');
h.push('.tcb{border-top:1px solid var(--bd)}');
h.push('.cr{display:flex;align-items:center;padding:5px 16px;font-size:12px;border-bottom:1px solid rgba(51,65,85,.5);gap:6px}');
h.push('.cr:last-child{border-bottom:none}');
h.push('.cr .ci{width:16px;text-align:center;flex-shrink:0}');
h.push('.cr .cn{font-weight:600;min-width:100px}');
h.push('.cr .ct2{color:var(--tm);flex:1;text-align:left;direction:ltr}');
h.push('.cr .fk{color:var(--ac);font-size:10px}');
h.push('.rl{display:flex;flex-direction:column;gap:8px}');
h.push('.rr{background:var(--sf);border:1px solid var(--bd);border-radius:8px;padding:12px 16px;display:flex;align-items:center;gap:12px;font-size:13px}');
h.push('.rt{background:var(--bg);border:1px solid var(--bd);padding:4px 10px;border-radius:6px;font-weight:600;white-space:nowrap}');
h.push('.ra{color:var(--ac);font-size:18px}');
h.push('.rp{font-size:11px;color:var(--tm);padding:2px 8px;background:var(--bg);border-radius:4px}');
h.push('.eg{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:12px}');
h.push('.ec{background:var(--sf);border:1px solid var(--bd);border-radius:8px;padding:14px 16px}');
h.push('.ec h3{font-size:14px;color:var(--a2);margin-bottom:8px}');
h.push('.ev{display:flex;flex-wrap:wrap;gap:4px}');
h.push('.evl{background:var(--bg);border:1px solid var(--bd);padding:3px 8px;border-radius:4px;font-size:11px;font-family:monospace}');
h.push('.ga{background:rgba(56,189,248,.15);border-color:rgba(56,189,248,.3)}.ga .tch{color:var(--ac)}');
h.push('.gs{background:rgba(52,211,153,.15);border-color:rgba(52,211,153,.3)}.gs .tch{color:var(--a3)}');
h.push('.gi{background:rgba(251,146,60,.15);border-color:rgba(251,146,60,.3)}.gi .tch{color:var(--a4)}');
h.push('.gt{background:rgba(244,114,182,.15);border-color:rgba(244,114,182,.3)}.gt .tch{color:var(--a5)}');
h.push('</style></head><body>');
// Header
h.push('<div class="hdr"><div><h1>ERD - Media Deck Database</h1><div class="sub">Database Schema Diagram | August 2026</div></div>');
h.push('<div class="stats"><div class="stat"><div class="n">14</div><div class="l">Tables</div></div><div class="stat"><div class="n">8</div><div class="l">Enums</div></div><div class="stat"><div class="n">14</div><div class="l">FK Relations</div></div></div></div>');
// Tabs
h.push('<div class="tabs"><button class="tab on" onclick="sw(\'erd\',this)">ERD Diagram</button><button class="tab" onclick="sw(\'tables\',this)">Table Details</button><button class="tab" onclick="sw(\'rels\',this)">Relations</button><button class="tab" onclick="sw(\'enums\',this)">Enum Types</button></div>');
h.push('<div class="ct">');
// ERD view
h.push('<div id="v-erd" class="v on"><div class="mermaid">');
h.push('erDiagram');
h.push('    workspaces { uuid id PK; text name; text slug UK; text logo_url }');
h.push('    profiles { uuid id PK; text full_name; app_role role; uuid workspace_id FK }');
h.push('    workspace_members { uuid id PK; uuid workspace_id FK; uuid user_id FK; app_role role }');
h.push('    social_accounts { uuid id PK; text brand; social_platform platform; text username; text display_name; text external_id; social_account_status status }');
h.push('    social_metrics { bigint id PK; uuid account_id FK; social_metric_period period; text period_label; bigint followers; bigint views; bigint likes; bigint reach; numeric engagement_rate }');
h.push('    social_followers { bigint id PK; text brand; text platform; text handle; text month; integer followers }');
h.push('    social_sync_logs { bigint id PK; uuid social_account_id FK; text status; integer records_fetched }');
h.push('    social_data_quality_reviews { uuid id PK; text issue_type; bigint metric_id FK; text field; text status }');
h.push('    social_metric_edit_logs { bigint id PK; bigint metric_id FK; text field; jsonb old_value; jsonb new_value }');
h.push('    import_sessions { uuid id PK; text filename; integer total_rows; import_session_status status }');
h.push('    import_rows { uuid id PK; uuid session_id FK; integer row_number; jsonb raw_data; uuid matched_account_id FK; import_row_status status }');
h.push('    import_audit_log { uuid id PK; uuid session_id FK; uuid row_id FK; text action }');
h.push('    tasks { text id PK; text parent_id FK; text title; task_status status; task_priority priority; text due_date; text color; text category }');
h.push('    task_labels { text id PK; text name; text color }');
h.push('    workspaces ||--o{ workspace_members : has');
h.push('    workspaces ||--o{ profiles : has');
h.push('    social_accounts ||--o{ social_metrics : has');
h.push('    social_accounts ||--o{ social_sync_logs : sync');
h.push('    social_accounts ||--o{ social_data_quality_reviews : issues');
h.push('    social_metrics ||--o{ social_metric_edit_logs : edit');
h.push('    social_metrics ||--o{ social_data_quality_reviews : issues');
h.push('    import_sessions ||--o{ import_rows : contains');
h.push('    import_sessions ||--o{ import_audit_log : audit');
h.push('    import_rows ||--o{ import_audit_log : actions');
h.push('    import_rows }o--o| social_accounts : matched');
h.push('    tasks ||--o{ tasks : subtasks');
h.push('</div><div style="text-align:center;color:var(--tm);font-size:12px">Zoom and pan supported</div></div>');
// Tables, Rels, Enums views generated by JS below
h.push('<div id="v-tables" class="v"><div class="g" id="tc"></div></div>');
h.push('<div id="v-rels" class="v"><div class="rl" id="rc"></div></div>');
h.push('<div id="v-enums" class="v"><div class="eg" id="ec"></div></div>');
h.push('</div>');
// Scripts
h.push('<script>');
h.push("mermaid.initialize({startOnLoad:true,theme:'dark',themeVar
